version: '3.8'

services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:prometheus

  prometheus:
    image: prom/prometheus:v3.2.1
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus:/etc/prometheus
    command:
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--storage.tsdb.retention.time=1h'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
      - '--web.route-prefix=/'
      - '--web.enable-otlp-receiver'
      - '--enable-feature=exemplar-storage'
    ports:
      - "9090:9090"

  hotrod:
    image: ghcr.io/dodopizza/dotnet-hotrod:main-c7ac0c5
    environment:
      - OTLP_ENDPOINT_URL=http://alloy:4318
      - OTEL_SERVICE_NAME=hotrod  
      - SLEEP=1

  alloy:
    image: grafana/alloy:latest
    ports:
      - "4318:4318"   # OTLP HTTP receiver
      - "12345:12345"
    command: 
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - /etc/alloy/config.alloy   
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy
    depends_on:
      - prometheus

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD_MUST_CHANGE=false
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  prometheus-data:
  grafana-data:
